# Generated by Django 4.0.2 on 2022-02-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_document_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_num',
            field=models.PositiveIntegerField(),
        ),
    ]
